### ISSUE TITLE
HW1:  "our Wiki" link points to 2016 course wiki

### ISSUE THREAD

**Issue by robmullr** [saasbook/AV102#46]
The link to "our Wiki" points to the 2016 spring running of AV102.  Points to "https://edge.edx.org/courses/course-v1:AgileVentures+AV102+2016_Spring/wiki/AgileVentures.AV102.2015_Fall/hw1-questions-might-have-helped-me-make-faster-pro/".  Should be updated to 2017 link.

**Comment by robmullr** [comment]
2017 link to wiki is:  "https://edge.edx.org/courses/course-v1:AgileVentures+AV102+Spring_2017/wiki/AgileVentures.AV102.2015_Fall/"

**Comment by tansaku** [comment]
thanks @robmullr - I've updated that.  
strangely all the wikis seem to be linked to the same underlying link - it all seems a bit confused ... not sure if there's some other helpful clean up we can do ...

**Comment by idfubar** [comment]
Some Slack comments suggested the headers returned a given learner to older versions of the course... but my attempts at reproducing the same, to date, have not been successful...

**Comment by idfubar** [comment]
20171002:

"Hi Edx Support,

Hope you're well.

I was wondering if there's an easy way for us to ensure that our TA training coures on edge edX have up to date wikis?

https://edge.edx.org/courses/course-v1:AgileVentures+AV102+2017_Fall/wiki/AgileVentures.AV102.2015_Fall/

I know edge is not supported in the same was as the main edx, but we use this course to train teaching assistants for the "Agile Development using Ruby on Rails" course (on main edX), and so any help here will benefit that course too.

I use the usual export and import tools to create new instances of the training course on edge, and at the moment that seems to leave the current course wiki pointing to the old wiki - which is great in that I want the students to be able to see the old wiki, but not so great as the navigation then ends up taking them back to an old instance of the course ...

What I'd really like to do is import the old wiki so that it's in the new course and all the URLs are consistently in the 2017_Fall course.  Have you any ideas about how to do this?

Many thanks in advance
Best, Sam"

20171003:

"It's great to hear from you, and thank you for contacting edX Partner Support. We unfortunately don't have a natural way of copying over wiki content, and I'm sorry I don't have better news. The two options, as you've outlined, are:
 - allow new courses to point to old, existing wikis (as you've found for the training courses)
 - allow new courses to point to new, empty wikis

The default behavior will be that each new course, even after import, should have its own new wiki. However, if one imports a course with a manually edited wiki slug in the course.xml file, the imported content will point to the manually edited wiki slug. Against this background, I suspect that all of your course imports have the line " <wiki slug="AgileVentures.AV102.2015_Fall"/>, and you do have the option of pointing the course to a new wiki instance by updating that line to the appropriate course ID. 

In fact, all the edge course wikis are connected indirectly via the wiki directory, and you can even find the provisioned, but empty, wikis for your newer courses - here's an link to an example search for courses with 'AV' in the title: https://edge.edx.org/courses/course-v1:AgileVentures+AV102+2017_Fall/wiki/_dir/?query=AV

I hope this helps clarify how the wikis work. I realize it doesn't facilitated what you'd like to do directly, but does lay out the options of what's available. I'm happy to pass along the suggestion of cloning wiki content more easily, but at the moment the most realistic option is to copy/paste existing pages.

Please let me know if there's anything else!"
