### ISSUE TITLE
PT or Waffle

### ISSUE THREAD

**Issue by mach1010** [saasbook/AV102#8]
PT is mentioned in several places; course issues are now being reported on waffle. The 169.x courses may still rely on PT so this may be relevant for preparing TA's for the course itself, but confusing for reporting bugs on the course.

**Comment by mach1010** [comment]
This vid covers PT, and is now live 
https://studio.edge.edx.org/container/block-v1:AgileVentures+AV102+2015_Fall+type@vertical+block@9ed50a3900d74a3f89a6f1ab80ddbfdd

**Comment by mach1010** [comment]
The second section, Distributed Software Development, has subsections that have released status, although the section isn't due to release until 9/8. They don't appear to be live to students when looking at the course so disregard previous comment about being live (although it does deal with PT).

**Comment by tansaku** [comment]
hi bill, as you worked out, yes they're not live yet - you can just see them because you are an admin, but you are right this is an issue.  I'd love to start using waffle, but don't know that I have time to update the videos.  The plan is for these videos to go live tonight ... in the first instance this waffle is more for AV102 admins like yourself rather than the students, but yes, feels like we might have to use PT for the main course for consistency, when I'd love to upgrade to waffle ...

**Comment by freeranger** [comment]
@tansaku perhaps this issue can be closed now?
